version: '3.9'
services:
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=modelshare
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass "redis"
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio/data:/data
    command: minio server /data --console-address ":9001"
    restart: unless-stopped
  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin && /usr/bin/mc mb --ignore-existing minio/modelshare && /usr/bin/mc anonymous set public minio/modelshare && /usr/bin/mc mb --ignore-existing minio/settled && /usr/bin/mc anonymous set public minio/settled && /usr/bin/mc mb --ignore-existing minio/images && /usr/bin/mc anonymous set public minio/images && exit 0"
    restart: unless-stopped
  maildev:
    image: maildev/maildev
    container_name: maildev
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
    ports:
      - 1025:1025
      - 1080:1080
    restart: unless-stopped
  clickhouse:
    image: clickhouse/clickhouse-server:head-alpine
    ports:
      - 8123:8123 # ClickHouse HTTP port
      - 9500:9008 # ClickHouse TCP port 
      - 9501:9009
    volumes:
      - /var/lib/docker/volumes/
    environment:
      - CLICKHOUSE_CONFIG=/etc/clickhouse-server/config.xml
    restart: unless-stopped
